- hosts: all
  become: true

  tasks:
    - name: ensure the repository is configured
      yum_repository: 
        name: jenkins
        description: 'Official Jenkins Yum Repo'
        baseurl: https://pkg.jenkins.io/redhat-stable/
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key 
        gpgcheck: yes
        # enabled=yes
        state: absent

    # - name: ensure jenkins is installed
    #   yum: name=jenkins update_cache=yes state=present

    # - name: ensure jenkins is running
    #   register: jenkinsrunning
    #   service: name=jenkins enabled=yes state=started

    - name: open firewall port
      ansible.posix.firewalld: 
        service: http
        permanent: yes
        state: enabled
        immediate: true
      vars:
        ansible_python_interpreter: /usr/bin/python2.7

    - name: notify slack - successfully installed jenkins
      community.general.slack:
        token: T05Q37QNH97/B05Q4056Y6M/q76qaZoerJCLg00q8MqlK7qD
        msg: |
            ### StatusUpdate ###
            – ------------------------------------
            ``
            `Server`: {{ansible_host}}
            `Status`: Ansible Jenkins Install Job Successful
            – ------------------------------------
        channel: '#automation-deployments'
        color: good
      delay: 30
      when: jenkinsrunning is not failed
      ignore_errors: true

    - name: notify slack - unsuccessful deployment
      community.general.slack:
        token: T05Q37QNH97/B05Q4056Y6M/q76qaZoerJCLg00q8MqlK7qD
        msg: |
            ### StatusUpdate ###
            – ------------------------------------
            ``
            `Server`: {{ansible_host}}
            `Status`: Ansible Jenkins Install Job NOT Successful
            – ------------------------------------
        channel: '#automation-deployments'
        color: warning
      delay: 30
      when: jenkinsrunning is failed
      ignore_errors: true    